name: Generate Index JSON

on:
  push:
    branches:
      - main
    paths:
      - "data/**"
      - "build.gradle"

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew generateIndexJson

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
